name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r "C:\Users\nuaga\OneDrive\Desktop\workflows\requirements.txt"

      - name: Run tests
        run: python -m unittest discover -s tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        run: |
          # Replace these with your actual Heroku deployment steps
          echo "Deploying application to Heroku..."
          # Add your Heroku deployment commands here (e.g., heroku login, git push heroku main, etc.)
